#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComprasContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WINCONT")]
	public partial class ComprasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCOMP_QUEDAN(ComprasDB.COMP_QUEDAN instance);
    partial void UpdateCOMP_QUEDAN(ComprasDB.COMP_QUEDAN instance);
    partial void DeleteCOMP_QUEDAN(ComprasDB.COMP_QUEDAN instance);
    partial void InsertCOMP_DETA_QUEDAN(ComprasDB.COMP_DETA_QUEDAN instance);
    partial void UpdateCOMP_DETA_QUEDAN(ComprasDB.COMP_DETA_QUEDAN instance);
    partial void DeleteCOMP_DETA_QUEDAN(ComprasDB.COMP_DETA_QUEDAN instance);
    partial void InsertCOMP_COMPRA(ComprasDB.COMP_COMPRA instance);
    partial void UpdateCOMP_COMPRA(ComprasDB.COMP_COMPRA instance);
    partial void DeleteCOMP_COMPRA(ComprasDB.COMP_COMPRA instance);
    #endregion
		
		public ComprasDataContext() : 
				base(global::winCont.Properties.Settings.Default.WINCONTConnectionString5, mappingSource)
		{
			OnCreated();
		}
		
		public ComprasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ComprasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ComprasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ComprasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ComprasDB.COMP_QUEDAN> COMP_QUEDAN
		{
			get
			{
				return this.GetTable<ComprasDB.COMP_QUEDAN>();
			}
		}
		
		public System.Data.Linq.Table<ComprasDB.COMP_DETA_QUEDAN> COMP_DETA_QUEDAN
		{
			get
			{
				return this.GetTable<ComprasDB.COMP_DETA_QUEDAN>();
			}
		}
		
		public System.Data.Linq.Table<ComprasDB.V_COMP_QUEDAN> V_COMP_QUEDAN
		{
			get
			{
				return this.GetTable<ComprasDB.V_COMP_QUEDAN>();
			}
		}
		
		public System.Data.Linq.Table<ComprasDB.COMP_COMPRA> COMP_COMPRA
		{
			get
			{
				return this.GetTable<ComprasDB.COMP_COMPRA>();
			}
		}
		
		public System.Data.Linq.Table<ComprasDB.V_COMP_COMPRA> V_COMP_COMPRA
		{
			get
			{
				return this.GetTable<ComprasDB.V_COMP_COMPRA>();
			}
		}
		
		public System.Data.Linq.Table<ComprasDB.V_COMP_DETA_QUEDAN> V_COMP_DETA_QUEDAN
		{
			get
			{
				return this.GetTable<ComprasDB.V_COMP_DETA_QUEDAN>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_COMP_ACTU_COMP")]
		public int PR_COMP_ACTU_COMP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_EMPRESA", DbType="Int")] System.Nullable<int> iD_EMPRESA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NM_ERROR", DbType="Int")] ref System.Nullable<int> nM_ERROR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSJ_ERROR", DbType="VarChar(100)")] ref string mSJ_ERROR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, iD_EMPRESA, nM_ERROR, mSJ_ERROR);
			nM_ERROR = ((System.Nullable<int>)(result.GetParameterValue(2)));
			mSJ_ERROR = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_COMP_IMPO_INGR_COMPR")]
		public int PR_COMP_IMPO_INGR_COMPR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_ING", DbType="Int")] System.Nullable<int> iD_ING, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_EMPRESA", DbType="Int")] System.Nullable<int> iD_EMPRESA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_COMP", DbType="Int")] ref System.Nullable<int> iD_COMP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NM_ERROR", DbType="Int")] ref System.Nullable<int> nM_ERROR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSJ_ERROR", DbType="VarChar(100)")] ref string mSJ_ERROR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_ING, iD_EMPRESA, iD_COMP, nM_ERROR, mSJ_ERROR);
			iD_COMP = ((System.Nullable<int>)(result.GetParameterValue(2)));
			nM_ERROR = ((System.Nullable<int>)(result.GetParameterValue(3)));
			mSJ_ERROR = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_CONT_GENE_CONT_COMP")]
		public void PR_CONT_GENE_CONT_COMP([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_COMPRA", DbType="Int")] System.Nullable<int> iD_COMPRA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NM_ERROR", DbType="Int")] ref System.Nullable<int> nM_ERROR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSJ_ERROR", DbType="VarChar(100)")] ref string mSJ_ERROR)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_COMPRA, nM_ERROR, mSJ_ERROR);
			nM_ERROR = ((System.Nullable<int>)(result.GetParameterValue(1)));
			mSJ_ERROR = ((string)(result.GetParameterValue(2)));
		}
	}
}
namespace ComprasDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMP_QUEDAN")]
	public partial class COMP_QUEDAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_EMPRESA;
		
		private System.Nullable<int> _NM_EJERCICIO;
		
		private System.Nullable<int> _NM_PERIODO;
		
		private System.Nullable<System.DateTime> _FE_FECHA;
		
		private System.Nullable<int> _ID_TERCERO;
		
		private System.Nullable<int> _ID_UBICACION_DEPT;
		
		private System.Nullable<int> _ID_TIPO_DOCUMENTO;
		
		private string _CD_SERIE;
		
		private System.Nullable<int> _CD_NUMERO;
		
		private System.Nullable<char> _CD_ESTADO;
		
		private EntitySet<COMP_DETA_QUEDAN> _COMP_DETA_QUEDAN;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_EMPRESAChanging(System.Nullable<int> value);
    partial void OnID_EMPRESAChanged();
    partial void OnNM_EJERCICIOChanging(System.Nullable<int> value);
    partial void OnNM_EJERCICIOChanged();
    partial void OnNM_PERIODOChanging(System.Nullable<int> value);
    partial void OnNM_PERIODOChanged();
    partial void OnFE_FECHAChanging(System.Nullable<System.DateTime> value);
    partial void OnFE_FECHAChanged();
    partial void OnID_TERCEROChanging(System.Nullable<int> value);
    partial void OnID_TERCEROChanged();
    partial void OnID_UBICACION_DEPTChanging(System.Nullable<int> value);
    partial void OnID_UBICACION_DEPTChanged();
    partial void OnID_TIPO_DOCUMENTOChanging(System.Nullable<int> value);
    partial void OnID_TIPO_DOCUMENTOChanged();
    partial void OnCD_SERIEChanging(string value);
    partial void OnCD_SERIEChanged();
    partial void OnCD_NUMEROChanging(System.Nullable<int> value);
    partial void OnCD_NUMEROChanged();
    partial void OnCD_ESTADOChanging(System.Nullable<char> value);
    partial void OnCD_ESTADOChanged();
    #endregion
		
		public COMP_QUEDAN()
		{
			this._COMP_DETA_QUEDAN = new EntitySet<COMP_DETA_QUEDAN>(new Action<COMP_DETA_QUEDAN>(this.attach_COMP_DETA_QUEDAN), new Action<COMP_DETA_QUEDAN>(this.detach_COMP_DETA_QUEDAN));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EMPRESA", DbType="Int")]
		public System.Nullable<int> ID_EMPRESA
		{
			get
			{
				return this._ID_EMPRESA;
			}
			set
			{
				if ((this._ID_EMPRESA != value))
				{
					this.OnID_EMPRESAChanging(value);
					this.SendPropertyChanging();
					this._ID_EMPRESA = value;
					this.SendPropertyChanged("ID_EMPRESA");
					this.OnID_EMPRESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_EJERCICIO", DbType="Int")]
		public System.Nullable<int> NM_EJERCICIO
		{
			get
			{
				return this._NM_EJERCICIO;
			}
			set
			{
				if ((this._NM_EJERCICIO != value))
				{
					this.OnNM_EJERCICIOChanging(value);
					this.SendPropertyChanging();
					this._NM_EJERCICIO = value;
					this.SendPropertyChanged("NM_EJERCICIO");
					this.OnNM_EJERCICIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_PERIODO", DbType="Int")]
		public System.Nullable<int> NM_PERIODO
		{
			get
			{
				return this._NM_PERIODO;
			}
			set
			{
				if ((this._NM_PERIODO != value))
				{
					this.OnNM_PERIODOChanging(value);
					this.SendPropertyChanging();
					this._NM_PERIODO = value;
					this.SendPropertyChanged("NM_PERIODO");
					this.OnNM_PERIODOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FE_FECHA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FE_FECHA
		{
			get
			{
				return this._FE_FECHA;
			}
			set
			{
				if ((this._FE_FECHA != value))
				{
					this.OnFE_FECHAChanging(value);
					this.SendPropertyChanging();
					this._FE_FECHA = value;
					this.SendPropertyChanged("FE_FECHA");
					this.OnFE_FECHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TERCERO", DbType="Int")]
		public System.Nullable<int> ID_TERCERO
		{
			get
			{
				return this._ID_TERCERO;
			}
			set
			{
				if ((this._ID_TERCERO != value))
				{
					this.OnID_TERCEROChanging(value);
					this.SendPropertyChanging();
					this._ID_TERCERO = value;
					this.SendPropertyChanged("ID_TERCERO");
					this.OnID_TERCEROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_UBICACION_DEPT", DbType="Int")]
		public System.Nullable<int> ID_UBICACION_DEPT
		{
			get
			{
				return this._ID_UBICACION_DEPT;
			}
			set
			{
				if ((this._ID_UBICACION_DEPT != value))
				{
					this.OnID_UBICACION_DEPTChanging(value);
					this.SendPropertyChanging();
					this._ID_UBICACION_DEPT = value;
					this.SendPropertyChanged("ID_UBICACION_DEPT");
					this.OnID_UBICACION_DEPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TIPO_DOCUMENTO", DbType="Int")]
		public System.Nullable<int> ID_TIPO_DOCUMENTO
		{
			get
			{
				return this._ID_TIPO_DOCUMENTO;
			}
			set
			{
				if ((this._ID_TIPO_DOCUMENTO != value))
				{
					this.OnID_TIPO_DOCUMENTOChanging(value);
					this.SendPropertyChanging();
					this._ID_TIPO_DOCUMENTO = value;
					this.SendPropertyChanged("ID_TIPO_DOCUMENTO");
					this.OnID_TIPO_DOCUMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_SERIE", DbType="VarChar(10)")]
		public string CD_SERIE
		{
			get
			{
				return this._CD_SERIE;
			}
			set
			{
				if ((this._CD_SERIE != value))
				{
					this.OnCD_SERIEChanging(value);
					this.SendPropertyChanging();
					this._CD_SERIE = value;
					this.SendPropertyChanged("CD_SERIE");
					this.OnCD_SERIEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_NUMERO", DbType="Int")]
		public System.Nullable<int> CD_NUMERO
		{
			get
			{
				return this._CD_NUMERO;
			}
			set
			{
				if ((this._CD_NUMERO != value))
				{
					this.OnCD_NUMEROChanging(value);
					this.SendPropertyChanging();
					this._CD_NUMERO = value;
					this.SendPropertyChanged("CD_NUMERO");
					this.OnCD_NUMEROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_ESTADO", DbType="Char(1)")]
		public System.Nullable<char> CD_ESTADO
		{
			get
			{
				return this._CD_ESTADO;
			}
			set
			{
				if ((this._CD_ESTADO != value))
				{
					this.OnCD_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._CD_ESTADO = value;
					this.SendPropertyChanged("CD_ESTADO");
					this.OnCD_ESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COMP_QUEDAN_COMP_DETA_QUEDAN", Storage="_COMP_DETA_QUEDAN", ThisKey="ID", OtherKey="ID_QUEDAN")]
		public EntitySet<COMP_DETA_QUEDAN> COMP_DETA_QUEDAN
		{
			get
			{
				return this._COMP_DETA_QUEDAN;
			}
			set
			{
				this._COMP_DETA_QUEDAN.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_COMP_DETA_QUEDAN(COMP_DETA_QUEDAN entity)
		{
			this.SendPropertyChanging();
			entity.COMP_QUEDAN = this;
		}
		
		private void detach_COMP_DETA_QUEDAN(COMP_DETA_QUEDAN entity)
		{
			this.SendPropertyChanging();
			entity.COMP_QUEDAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMP_DETA_QUEDAN")]
	public partial class COMP_DETA_QUEDAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ID_QUEDAN;
		
		private System.Nullable<int> _ID_COMPRA;
		
		private EntityRef<COMP_QUEDAN> _COMP_QUEDAN;
		
		private EntityRef<COMP_COMPRA> _COMP_COMPRA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_QUEDANChanging(System.Nullable<int> value);
    partial void OnID_QUEDANChanged();
    partial void OnID_COMPRAChanging(System.Nullable<int> value);
    partial void OnID_COMPRAChanged();
    #endregion
		
		public COMP_DETA_QUEDAN()
		{
			this._COMP_QUEDAN = default(EntityRef<COMP_QUEDAN>);
			this._COMP_COMPRA = default(EntityRef<COMP_COMPRA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_QUEDAN", DbType="Int")]
		public System.Nullable<int> ID_QUEDAN
		{
			get
			{
				return this._ID_QUEDAN;
			}
			set
			{
				if ((this._ID_QUEDAN != value))
				{
					if (this._COMP_QUEDAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_QUEDANChanging(value);
					this.SendPropertyChanging();
					this._ID_QUEDAN = value;
					this.SendPropertyChanged("ID_QUEDAN");
					this.OnID_QUEDANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_COMPRA", DbType="Int")]
		public System.Nullable<int> ID_COMPRA
		{
			get
			{
				return this._ID_COMPRA;
			}
			set
			{
				if ((this._ID_COMPRA != value))
				{
					if (this._COMP_COMPRA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_COMPRAChanging(value);
					this.SendPropertyChanging();
					this._ID_COMPRA = value;
					this.SendPropertyChanged("ID_COMPRA");
					this.OnID_COMPRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COMP_QUEDAN_COMP_DETA_QUEDAN", Storage="_COMP_QUEDAN", ThisKey="ID_QUEDAN", OtherKey="ID", IsForeignKey=true)]
		public COMP_QUEDAN COMP_QUEDAN
		{
			get
			{
				return this._COMP_QUEDAN.Entity;
			}
			set
			{
				COMP_QUEDAN previousValue = this._COMP_QUEDAN.Entity;
				if (((previousValue != value) 
							|| (this._COMP_QUEDAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._COMP_QUEDAN.Entity = null;
						previousValue.COMP_DETA_QUEDAN.Remove(this);
					}
					this._COMP_QUEDAN.Entity = value;
					if ((value != null))
					{
						value.COMP_DETA_QUEDAN.Add(this);
						this._ID_QUEDAN = value.ID;
					}
					else
					{
						this._ID_QUEDAN = default(Nullable<int>);
					}
					this.SendPropertyChanged("COMP_QUEDAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COMP_COMPRA_COMP_DETA_QUEDAN", Storage="_COMP_COMPRA", ThisKey="ID_COMPRA", OtherKey="ID", IsForeignKey=true)]
		public COMP_COMPRA COMP_COMPRA
		{
			get
			{
				return this._COMP_COMPRA.Entity;
			}
			set
			{
				COMP_COMPRA previousValue = this._COMP_COMPRA.Entity;
				if (((previousValue != value) 
							|| (this._COMP_COMPRA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._COMP_COMPRA.Entity = null;
						previousValue.COMP_DETA_QUEDAN.Remove(this);
					}
					this._COMP_COMPRA.Entity = value;
					if ((value != null))
					{
						value.COMP_DETA_QUEDAN.Add(this);
						this._ID_COMPRA = value.ID;
					}
					else
					{
						this._ID_COMPRA = default(Nullable<int>);
					}
					this.SendPropertyChanged("COMP_COMPRA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_COMP_QUEDAN")]
	public partial class V_COMP_QUEDAN
	{
		
		private int _ID;
		
		private System.Nullable<int> _ID_EMPRESA;
		
		private System.Nullable<int> _NM_EJERCICIO;
		
		private System.Nullable<int> _NM_PERIODO;
		
		private System.Nullable<int> _ID_UBICACION_DEPT;
		
		private System.Nullable<int> _ID_TIPO_DOCUMENTO;
		
		private string _CD_SERIE;
		
		private System.Nullable<int> _CD_NUMERO;
		
		private System.Nullable<System.DateTime> _FE_FECHA;
		
		private System.Nullable<int> _ID_TERCERO;
		
		private System.Nullable<char> _CD_ESTADO;
		
		private string _DS_NOMBRE;
		
		private string _DS_DOCUMENTO;
		
		private string _DS_UBICACION;
		
		private string _DS_NM_RF;
		
		private string _DS_NM_NIT;
		
		private string _DS_NM_DUI;
		
		private string _DS_RZN_COMER;
		
		public V_COMP_QUEDAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EMPRESA", DbType="Int")]
		public System.Nullable<int> ID_EMPRESA
		{
			get
			{
				return this._ID_EMPRESA;
			}
			set
			{
				if ((this._ID_EMPRESA != value))
				{
					this._ID_EMPRESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_EJERCICIO", DbType="Int")]
		public System.Nullable<int> NM_EJERCICIO
		{
			get
			{
				return this._NM_EJERCICIO;
			}
			set
			{
				if ((this._NM_EJERCICIO != value))
				{
					this._NM_EJERCICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_PERIODO", DbType="Int")]
		public System.Nullable<int> NM_PERIODO
		{
			get
			{
				return this._NM_PERIODO;
			}
			set
			{
				if ((this._NM_PERIODO != value))
				{
					this._NM_PERIODO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_UBICACION_DEPT", DbType="Int")]
		public System.Nullable<int> ID_UBICACION_DEPT
		{
			get
			{
				return this._ID_UBICACION_DEPT;
			}
			set
			{
				if ((this._ID_UBICACION_DEPT != value))
				{
					this._ID_UBICACION_DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TIPO_DOCUMENTO", DbType="Int")]
		public System.Nullable<int> ID_TIPO_DOCUMENTO
		{
			get
			{
				return this._ID_TIPO_DOCUMENTO;
			}
			set
			{
				if ((this._ID_TIPO_DOCUMENTO != value))
				{
					this._ID_TIPO_DOCUMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_SERIE", DbType="VarChar(10)")]
		public string CD_SERIE
		{
			get
			{
				return this._CD_SERIE;
			}
			set
			{
				if ((this._CD_SERIE != value))
				{
					this._CD_SERIE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_NUMERO", DbType="Int")]
		public System.Nullable<int> CD_NUMERO
		{
			get
			{
				return this._CD_NUMERO;
			}
			set
			{
				if ((this._CD_NUMERO != value))
				{
					this._CD_NUMERO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FE_FECHA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FE_FECHA
		{
			get
			{
				return this._FE_FECHA;
			}
			set
			{
				if ((this._FE_FECHA != value))
				{
					this._FE_FECHA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TERCERO", DbType="Int")]
		public System.Nullable<int> ID_TERCERO
		{
			get
			{
				return this._ID_TERCERO;
			}
			set
			{
				if ((this._ID_TERCERO != value))
				{
					this._ID_TERCERO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_ESTADO", DbType="Char(1)")]
		public System.Nullable<char> CD_ESTADO
		{
			get
			{
				return this._CD_ESTADO;
			}
			set
			{
				if ((this._CD_ESTADO != value))
				{
					this._CD_ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_NOMBRE", DbType="VarChar(200)")]
		public string DS_NOMBRE
		{
			get
			{
				return this._DS_NOMBRE;
			}
			set
			{
				if ((this._DS_NOMBRE != value))
				{
					this._DS_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_DOCUMENTO", DbType="VarChar(100)")]
		public string DS_DOCUMENTO
		{
			get
			{
				return this._DS_DOCUMENTO;
			}
			set
			{
				if ((this._DS_DOCUMENTO != value))
				{
					this._DS_DOCUMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_UBICACION", DbType="VarChar(50)")]
		public string DS_UBICACION
		{
			get
			{
				return this._DS_UBICACION;
			}
			set
			{
				if ((this._DS_UBICACION != value))
				{
					this._DS_UBICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_NM_RF", DbType="VarChar(20)")]
		public string DS_NM_RF
		{
			get
			{
				return this._DS_NM_RF;
			}
			set
			{
				if ((this._DS_NM_RF != value))
				{
					this._DS_NM_RF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_NM_NIT", DbType="VarChar(17)")]
		public string DS_NM_NIT
		{
			get
			{
				return this._DS_NM_NIT;
			}
			set
			{
				if ((this._DS_NM_NIT != value))
				{
					this._DS_NM_NIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_NM_DUI", DbType="VarChar(10)")]
		public string DS_NM_DUI
		{
			get
			{
				return this._DS_NM_DUI;
			}
			set
			{
				if ((this._DS_NM_DUI != value))
				{
					this._DS_NM_DUI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_RZN_COMER", DbType="VarChar(200)")]
		public string DS_RZN_COMER
		{
			get
			{
				return this._DS_RZN_COMER;
			}
			set
			{
				if ((this._DS_RZN_COMER != value))
				{
					this._DS_RZN_COMER = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMP_COMPRA")]
	public partial class COMP_COMPRA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _ID_EMPRESA;
		
		private int _NM_EJERCICIO;
		
		private int _NM_PERIODO;
		
		private int _ID_TERCERO;
		
		private char _FLG_CREDITO;
		
		private System.Nullable<System.DateTime> _FE_FECHA;
		
		private System.Nullable<System.DateTime> _FE_RECEPCION;
		
		private System.Nullable<System.DateTime> _FE_VENCIMIENTO;
		
		private int _ID_TIPO_DOCUMENTO;
		
		private string _CD_SERIE;
		
		private System.Nullable<int> _CD_NUMERO;
		
		private System.Nullable<decimal> _NM_GRAVADO;
		
		private System.Nullable<decimal> _NM_EXENTO;
		
		private System.Nullable<decimal> _NM_SUJETO_A_RENTA;
		
		private System.Nullable<decimal> _NM_IVA;
		
		private System.Nullable<decimal> _NM_RETENCION;
		
		private System.Nullable<decimal> _NM_PERCEPCION;
		
		private System.Nullable<decimal> _NM_RENTA;
		
		private System.Nullable<decimal> _NM_SALDO;
		
		private System.Nullable<decimal> _NM_TOTAL;
		
		private System.Nullable<char> _CD_ESTADO;
		
		private System.Nullable<char> _CD_ESTA_CONTA;
		
		private System.Nullable<char> _FLG_IMPO;
		
		private System.Nullable<int> _ID_PART_PRFM;
		
		private System.Nullable<int> _ID_INGRESO;
		
		private EntitySet<COMP_DETA_QUEDAN> _COMP_DETA_QUEDAN;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnID_EMPRESAChanging(int value);
    partial void OnID_EMPRESAChanged();
    partial void OnNM_EJERCICIOChanging(int value);
    partial void OnNM_EJERCICIOChanged();
    partial void OnNM_PERIODOChanging(int value);
    partial void OnNM_PERIODOChanged();
    partial void OnID_TERCEROChanging(int value);
    partial void OnID_TERCEROChanged();
    partial void OnFLG_CREDITOChanging(char value);
    partial void OnFLG_CREDITOChanged();
    partial void OnFE_FECHAChanging(System.Nullable<System.DateTime> value);
    partial void OnFE_FECHAChanged();
    partial void OnFE_RECEPCIONChanging(System.Nullable<System.DateTime> value);
    partial void OnFE_RECEPCIONChanged();
    partial void OnFE_VENCIMIENTOChanging(System.Nullable<System.DateTime> value);
    partial void OnFE_VENCIMIENTOChanged();
    partial void OnID_TIPO_DOCUMENTOChanging(int value);
    partial void OnID_TIPO_DOCUMENTOChanged();
    partial void OnCD_SERIEChanging(string value);
    partial void OnCD_SERIEChanged();
    partial void OnCD_NUMEROChanging(System.Nullable<int> value);
    partial void OnCD_NUMEROChanged();
    partial void OnNM_GRAVADOChanging(System.Nullable<decimal> value);
    partial void OnNM_GRAVADOChanged();
    partial void OnNM_EXENTOChanging(System.Nullable<decimal> value);
    partial void OnNM_EXENTOChanged();
    partial void OnNM_SUJETO_A_RENTAChanging(System.Nullable<decimal> value);
    partial void OnNM_SUJETO_A_RENTAChanged();
    partial void OnNM_IVAChanging(System.Nullable<decimal> value);
    partial void OnNM_IVAChanged();
    partial void OnNM_RETENCIONChanging(System.Nullable<decimal> value);
    partial void OnNM_RETENCIONChanged();
    partial void OnNM_PERCEPCIONChanging(System.Nullable<decimal> value);
    partial void OnNM_PERCEPCIONChanged();
    partial void OnNM_RENTAChanging(System.Nullable<decimal> value);
    partial void OnNM_RENTAChanged();
    partial void OnNM_SALDOChanging(System.Nullable<decimal> value);
    partial void OnNM_SALDOChanged();
    partial void OnNM_TOTALChanging(System.Nullable<decimal> value);
    partial void OnNM_TOTALChanged();
    partial void OnCD_ESTADOChanging(System.Nullable<char> value);
    partial void OnCD_ESTADOChanged();
    partial void OnCD_ESTA_CONTAChanging(System.Nullable<char> value);
    partial void OnCD_ESTA_CONTAChanged();
    partial void OnFLG_IMPOChanging(System.Nullable<char> value);
    partial void OnFLG_IMPOChanged();
    partial void OnID_PART_PRFMChanging(System.Nullable<int> value);
    partial void OnID_PART_PRFMChanged();
    partial void OnID_INGRESOChanging(System.Nullable<int> value);
    partial void OnID_INGRESOChanged();
    #endregion
		
		public COMP_COMPRA()
		{
			this._COMP_DETA_QUEDAN = new EntitySet<COMP_DETA_QUEDAN>(new Action<COMP_DETA_QUEDAN>(this.attach_COMP_DETA_QUEDAN), new Action<COMP_DETA_QUEDAN>(this.detach_COMP_DETA_QUEDAN));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EMPRESA", DbType="Int NOT NULL")]
		public int ID_EMPRESA
		{
			get
			{
				return this._ID_EMPRESA;
			}
			set
			{
				if ((this._ID_EMPRESA != value))
				{
					this.OnID_EMPRESAChanging(value);
					this.SendPropertyChanging();
					this._ID_EMPRESA = value;
					this.SendPropertyChanged("ID_EMPRESA");
					this.OnID_EMPRESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_EJERCICIO", DbType="Int NOT NULL")]
		public int NM_EJERCICIO
		{
			get
			{
				return this._NM_EJERCICIO;
			}
			set
			{
				if ((this._NM_EJERCICIO != value))
				{
					this.OnNM_EJERCICIOChanging(value);
					this.SendPropertyChanging();
					this._NM_EJERCICIO = value;
					this.SendPropertyChanged("NM_EJERCICIO");
					this.OnNM_EJERCICIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_PERIODO", DbType="Int NOT NULL")]
		public int NM_PERIODO
		{
			get
			{
				return this._NM_PERIODO;
			}
			set
			{
				if ((this._NM_PERIODO != value))
				{
					this.OnNM_PERIODOChanging(value);
					this.SendPropertyChanging();
					this._NM_PERIODO = value;
					this.SendPropertyChanged("NM_PERIODO");
					this.OnNM_PERIODOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TERCERO", DbType="Int NOT NULL")]
		public int ID_TERCERO
		{
			get
			{
				return this._ID_TERCERO;
			}
			set
			{
				if ((this._ID_TERCERO != value))
				{
					this.OnID_TERCEROChanging(value);
					this.SendPropertyChanging();
					this._ID_TERCERO = value;
					this.SendPropertyChanged("ID_TERCERO");
					this.OnID_TERCEROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLG_CREDITO", DbType="Char(1) NOT NULL")]
		public char FLG_CREDITO
		{
			get
			{
				return this._FLG_CREDITO;
			}
			set
			{
				if ((this._FLG_CREDITO != value))
				{
					this.OnFLG_CREDITOChanging(value);
					this.SendPropertyChanging();
					this._FLG_CREDITO = value;
					this.SendPropertyChanged("FLG_CREDITO");
					this.OnFLG_CREDITOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FE_FECHA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FE_FECHA
		{
			get
			{
				return this._FE_FECHA;
			}
			set
			{
				if ((this._FE_FECHA != value))
				{
					this.OnFE_FECHAChanging(value);
					this.SendPropertyChanging();
					this._FE_FECHA = value;
					this.SendPropertyChanged("FE_FECHA");
					this.OnFE_FECHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FE_RECEPCION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FE_RECEPCION
		{
			get
			{
				return this._FE_RECEPCION;
			}
			set
			{
				if ((this._FE_RECEPCION != value))
				{
					this.OnFE_RECEPCIONChanging(value);
					this.SendPropertyChanging();
					this._FE_RECEPCION = value;
					this.SendPropertyChanged("FE_RECEPCION");
					this.OnFE_RECEPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FE_VENCIMIENTO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FE_VENCIMIENTO
		{
			get
			{
				return this._FE_VENCIMIENTO;
			}
			set
			{
				if ((this._FE_VENCIMIENTO != value))
				{
					this.OnFE_VENCIMIENTOChanging(value);
					this.SendPropertyChanging();
					this._FE_VENCIMIENTO = value;
					this.SendPropertyChanged("FE_VENCIMIENTO");
					this.OnFE_VENCIMIENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TIPO_DOCUMENTO", DbType="Int NOT NULL")]
		public int ID_TIPO_DOCUMENTO
		{
			get
			{
				return this._ID_TIPO_DOCUMENTO;
			}
			set
			{
				if ((this._ID_TIPO_DOCUMENTO != value))
				{
					this.OnID_TIPO_DOCUMENTOChanging(value);
					this.SendPropertyChanging();
					this._ID_TIPO_DOCUMENTO = value;
					this.SendPropertyChanged("ID_TIPO_DOCUMENTO");
					this.OnID_TIPO_DOCUMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_SERIE", DbType="VarChar(10)")]
		public string CD_SERIE
		{
			get
			{
				return this._CD_SERIE;
			}
			set
			{
				if ((this._CD_SERIE != value))
				{
					this.OnCD_SERIEChanging(value);
					this.SendPropertyChanging();
					this._CD_SERIE = value;
					this.SendPropertyChanged("CD_SERIE");
					this.OnCD_SERIEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_NUMERO", DbType="Int")]
		public System.Nullable<int> CD_NUMERO
		{
			get
			{
				return this._CD_NUMERO;
			}
			set
			{
				if ((this._CD_NUMERO != value))
				{
					this.OnCD_NUMEROChanging(value);
					this.SendPropertyChanging();
					this._CD_NUMERO = value;
					this.SendPropertyChanged("CD_NUMERO");
					this.OnCD_NUMEROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_GRAVADO", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_GRAVADO
		{
			get
			{
				return this._NM_GRAVADO;
			}
			set
			{
				if ((this._NM_GRAVADO != value))
				{
					this.OnNM_GRAVADOChanging(value);
					this.SendPropertyChanging();
					this._NM_GRAVADO = value;
					this.SendPropertyChanged("NM_GRAVADO");
					this.OnNM_GRAVADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_EXENTO", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_EXENTO
		{
			get
			{
				return this._NM_EXENTO;
			}
			set
			{
				if ((this._NM_EXENTO != value))
				{
					this.OnNM_EXENTOChanging(value);
					this.SendPropertyChanging();
					this._NM_EXENTO = value;
					this.SendPropertyChanged("NM_EXENTO");
					this.OnNM_EXENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_SUJETO_A_RENTA", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_SUJETO_A_RENTA
		{
			get
			{
				return this._NM_SUJETO_A_RENTA;
			}
			set
			{
				if ((this._NM_SUJETO_A_RENTA != value))
				{
					this.OnNM_SUJETO_A_RENTAChanging(value);
					this.SendPropertyChanging();
					this._NM_SUJETO_A_RENTA = value;
					this.SendPropertyChanged("NM_SUJETO_A_RENTA");
					this.OnNM_SUJETO_A_RENTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_IVA", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_IVA
		{
			get
			{
				return this._NM_IVA;
			}
			set
			{
				if ((this._NM_IVA != value))
				{
					this.OnNM_IVAChanging(value);
					this.SendPropertyChanging();
					this._NM_IVA = value;
					this.SendPropertyChanged("NM_IVA");
					this.OnNM_IVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_RETENCION", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_RETENCION
		{
			get
			{
				return this._NM_RETENCION;
			}
			set
			{
				if ((this._NM_RETENCION != value))
				{
					this.OnNM_RETENCIONChanging(value);
					this.SendPropertyChanging();
					this._NM_RETENCION = value;
					this.SendPropertyChanged("NM_RETENCION");
					this.OnNM_RETENCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_PERCEPCION", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_PERCEPCION
		{
			get
			{
				return this._NM_PERCEPCION;
			}
			set
			{
				if ((this._NM_PERCEPCION != value))
				{
					this.OnNM_PERCEPCIONChanging(value);
					this.SendPropertyChanging();
					this._NM_PERCEPCION = value;
					this.SendPropertyChanged("NM_PERCEPCION");
					this.OnNM_PERCEPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_RENTA", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_RENTA
		{
			get
			{
				return this._NM_RENTA;
			}
			set
			{
				if ((this._NM_RENTA != value))
				{
					this.OnNM_RENTAChanging(value);
					this.SendPropertyChanging();
					this._NM_RENTA = value;
					this.SendPropertyChanged("NM_RENTA");
					this.OnNM_RENTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_SALDO", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_SALDO
		{
			get
			{
				return this._NM_SALDO;
			}
			set
			{
				if ((this._NM_SALDO != value))
				{
					this.OnNM_SALDOChanging(value);
					this.SendPropertyChanging();
					this._NM_SALDO = value;
					this.SendPropertyChanged("NM_SALDO");
					this.OnNM_SALDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_TOTAL", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_TOTAL
		{
			get
			{
				return this._NM_TOTAL;
			}
			set
			{
				if ((this._NM_TOTAL != value))
				{
					this.OnNM_TOTALChanging(value);
					this.SendPropertyChanging();
					this._NM_TOTAL = value;
					this.SendPropertyChanged("NM_TOTAL");
					this.OnNM_TOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_ESTADO", DbType="Char(1)")]
		public System.Nullable<char> CD_ESTADO
		{
			get
			{
				return this._CD_ESTADO;
			}
			set
			{
				if ((this._CD_ESTADO != value))
				{
					this.OnCD_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._CD_ESTADO = value;
					this.SendPropertyChanged("CD_ESTADO");
					this.OnCD_ESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_ESTA_CONTA", DbType="Char(1)")]
		public System.Nullable<char> CD_ESTA_CONTA
		{
			get
			{
				return this._CD_ESTA_CONTA;
			}
			set
			{
				if ((this._CD_ESTA_CONTA != value))
				{
					this.OnCD_ESTA_CONTAChanging(value);
					this.SendPropertyChanging();
					this._CD_ESTA_CONTA = value;
					this.SendPropertyChanged("CD_ESTA_CONTA");
					this.OnCD_ESTA_CONTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLG_IMPO", DbType="Char(1)")]
		public System.Nullable<char> FLG_IMPO
		{
			get
			{
				return this._FLG_IMPO;
			}
			set
			{
				if ((this._FLG_IMPO != value))
				{
					this.OnFLG_IMPOChanging(value);
					this.SendPropertyChanging();
					this._FLG_IMPO = value;
					this.SendPropertyChanged("FLG_IMPO");
					this.OnFLG_IMPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PART_PRFM", DbType="Int")]
		public System.Nullable<int> ID_PART_PRFM
		{
			get
			{
				return this._ID_PART_PRFM;
			}
			set
			{
				if ((this._ID_PART_PRFM != value))
				{
					this.OnID_PART_PRFMChanging(value);
					this.SendPropertyChanging();
					this._ID_PART_PRFM = value;
					this.SendPropertyChanged("ID_PART_PRFM");
					this.OnID_PART_PRFMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_INGRESO", DbType="Int")]
		public System.Nullable<int> ID_INGRESO
		{
			get
			{
				return this._ID_INGRESO;
			}
			set
			{
				if ((this._ID_INGRESO != value))
				{
					this.OnID_INGRESOChanging(value);
					this.SendPropertyChanging();
					this._ID_INGRESO = value;
					this.SendPropertyChanged("ID_INGRESO");
					this.OnID_INGRESOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COMP_COMPRA_COMP_DETA_QUEDAN", Storage="_COMP_DETA_QUEDAN", ThisKey="ID", OtherKey="ID_COMPRA")]
		public EntitySet<COMP_DETA_QUEDAN> COMP_DETA_QUEDAN
		{
			get
			{
				return this._COMP_DETA_QUEDAN;
			}
			set
			{
				this._COMP_DETA_QUEDAN.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_COMP_DETA_QUEDAN(COMP_DETA_QUEDAN entity)
		{
			this.SendPropertyChanging();
			entity.COMP_COMPRA = this;
		}
		
		private void detach_COMP_DETA_QUEDAN(COMP_DETA_QUEDAN entity)
		{
			this.SendPropertyChanging();
			entity.COMP_COMPRA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_COMP_COMPRA")]
	public partial class V_COMP_COMPRA
	{
		
		private int _ID;
		
		private int _ID_EMPRESA;
		
		private int _NM_EJERCICIO;
		
		private int _NM_PERIODO;
		
		private int _ID_TERCERO;
		
		private System.Nullable<System.DateTime> _FE_FECHA;
		
		private System.Nullable<System.DateTime> _FE_VENCIMIENTO;
		
		private System.Nullable<System.DateTime> _FE_RECEPCION;
		
		private int _ID_TIPO_DOCUMENTO;
		
		private string _CD_SERIE;
		
		private System.Nullable<int> _CD_NUMERO;
		
		private System.Nullable<decimal> _NM_GRAVADO;
		
		private System.Nullable<decimal> _NM_EXENTO;
		
		private System.Nullable<decimal> _NM_SUJETO_A_RENTA;
		
		private System.Nullable<decimal> _NM_IVA;
		
		private System.Nullable<decimal> _NM_RETENCION;
		
		private System.Nullable<decimal> _NM_RENTA;
		
		private System.Nullable<decimal> _NM_SALDO;
		
		private System.Nullable<char> _CD_ESTADO;
		
		private string _DS_NOMBRE;
		
		private string _DS_DIRECCION;
		
		private string _DS_RZN_COMER;
		
		private string _DS_NM_RF;
		
		private string _DS_NM_NIT;
		
		private string _DS_NM_DUI;
		
		private char _FLG_CREDITO;
		
		private string _DS_DOCUMENTO;
		
		private System.Nullable<decimal> _NM_TOTAL;
		
		private System.Nullable<char> _FLG_IMPO;
		
		private System.Nullable<int> _ID_PART_PRFM;
		
		private System.Nullable<char> _CD_ESTA_CONTA;
		
		private System.Nullable<int> _ID_INGRESO;
		
		private string _DS_CONDICION;
		
		public V_COMP_COMPRA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_EMPRESA", DbType="Int NOT NULL")]
		public int ID_EMPRESA
		{
			get
			{
				return this._ID_EMPRESA;
			}
			set
			{
				if ((this._ID_EMPRESA != value))
				{
					this._ID_EMPRESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_EJERCICIO", DbType="Int NOT NULL")]
		public int NM_EJERCICIO
		{
			get
			{
				return this._NM_EJERCICIO;
			}
			set
			{
				if ((this._NM_EJERCICIO != value))
				{
					this._NM_EJERCICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_PERIODO", DbType="Int NOT NULL")]
		public int NM_PERIODO
		{
			get
			{
				return this._NM_PERIODO;
			}
			set
			{
				if ((this._NM_PERIODO != value))
				{
					this._NM_PERIODO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TERCERO", DbType="Int NOT NULL")]
		public int ID_TERCERO
		{
			get
			{
				return this._ID_TERCERO;
			}
			set
			{
				if ((this._ID_TERCERO != value))
				{
					this._ID_TERCERO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FE_FECHA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FE_FECHA
		{
			get
			{
				return this._FE_FECHA;
			}
			set
			{
				if ((this._FE_FECHA != value))
				{
					this._FE_FECHA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FE_VENCIMIENTO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FE_VENCIMIENTO
		{
			get
			{
				return this._FE_VENCIMIENTO;
			}
			set
			{
				if ((this._FE_VENCIMIENTO != value))
				{
					this._FE_VENCIMIENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FE_RECEPCION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FE_RECEPCION
		{
			get
			{
				return this._FE_RECEPCION;
			}
			set
			{
				if ((this._FE_RECEPCION != value))
				{
					this._FE_RECEPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TIPO_DOCUMENTO", DbType="Int NOT NULL")]
		public int ID_TIPO_DOCUMENTO
		{
			get
			{
				return this._ID_TIPO_DOCUMENTO;
			}
			set
			{
				if ((this._ID_TIPO_DOCUMENTO != value))
				{
					this._ID_TIPO_DOCUMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_SERIE", DbType="VarChar(10)")]
		public string CD_SERIE
		{
			get
			{
				return this._CD_SERIE;
			}
			set
			{
				if ((this._CD_SERIE != value))
				{
					this._CD_SERIE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_NUMERO", DbType="Int")]
		public System.Nullable<int> CD_NUMERO
		{
			get
			{
				return this._CD_NUMERO;
			}
			set
			{
				if ((this._CD_NUMERO != value))
				{
					this._CD_NUMERO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_GRAVADO", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_GRAVADO
		{
			get
			{
				return this._NM_GRAVADO;
			}
			set
			{
				if ((this._NM_GRAVADO != value))
				{
					this._NM_GRAVADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_EXENTO", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_EXENTO
		{
			get
			{
				return this._NM_EXENTO;
			}
			set
			{
				if ((this._NM_EXENTO != value))
				{
					this._NM_EXENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_SUJETO_A_RENTA", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_SUJETO_A_RENTA
		{
			get
			{
				return this._NM_SUJETO_A_RENTA;
			}
			set
			{
				if ((this._NM_SUJETO_A_RENTA != value))
				{
					this._NM_SUJETO_A_RENTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_IVA", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_IVA
		{
			get
			{
				return this._NM_IVA;
			}
			set
			{
				if ((this._NM_IVA != value))
				{
					this._NM_IVA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_RETENCION", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_RETENCION
		{
			get
			{
				return this._NM_RETENCION;
			}
			set
			{
				if ((this._NM_RETENCION != value))
				{
					this._NM_RETENCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_RENTA", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_RENTA
		{
			get
			{
				return this._NM_RENTA;
			}
			set
			{
				if ((this._NM_RENTA != value))
				{
					this._NM_RENTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_SALDO", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_SALDO
		{
			get
			{
				return this._NM_SALDO;
			}
			set
			{
				if ((this._NM_SALDO != value))
				{
					this._NM_SALDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_ESTADO", DbType="Char(1)")]
		public System.Nullable<char> CD_ESTADO
		{
			get
			{
				return this._CD_ESTADO;
			}
			set
			{
				if ((this._CD_ESTADO != value))
				{
					this._CD_ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_NOMBRE", DbType="VarChar(200)")]
		public string DS_NOMBRE
		{
			get
			{
				return this._DS_NOMBRE;
			}
			set
			{
				if ((this._DS_NOMBRE != value))
				{
					this._DS_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_DIRECCION", DbType="VarChar(500)")]
		public string DS_DIRECCION
		{
			get
			{
				return this._DS_DIRECCION;
			}
			set
			{
				if ((this._DS_DIRECCION != value))
				{
					this._DS_DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_RZN_COMER", DbType="VarChar(200)")]
		public string DS_RZN_COMER
		{
			get
			{
				return this._DS_RZN_COMER;
			}
			set
			{
				if ((this._DS_RZN_COMER != value))
				{
					this._DS_RZN_COMER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_NM_RF", DbType="VarChar(20)")]
		public string DS_NM_RF
		{
			get
			{
				return this._DS_NM_RF;
			}
			set
			{
				if ((this._DS_NM_RF != value))
				{
					this._DS_NM_RF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_NM_NIT", DbType="VarChar(17)")]
		public string DS_NM_NIT
		{
			get
			{
				return this._DS_NM_NIT;
			}
			set
			{
				if ((this._DS_NM_NIT != value))
				{
					this._DS_NM_NIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_NM_DUI", DbType="VarChar(10)")]
		public string DS_NM_DUI
		{
			get
			{
				return this._DS_NM_DUI;
			}
			set
			{
				if ((this._DS_NM_DUI != value))
				{
					this._DS_NM_DUI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLG_CREDITO", DbType="Char(1) NOT NULL")]
		public char FLG_CREDITO
		{
			get
			{
				return this._FLG_CREDITO;
			}
			set
			{
				if ((this._FLG_CREDITO != value))
				{
					this._FLG_CREDITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_DOCUMENTO", DbType="VarChar(100)")]
		public string DS_DOCUMENTO
		{
			get
			{
				return this._DS_DOCUMENTO;
			}
			set
			{
				if ((this._DS_DOCUMENTO != value))
				{
					this._DS_DOCUMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_TOTAL", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_TOTAL
		{
			get
			{
				return this._NM_TOTAL;
			}
			set
			{
				if ((this._NM_TOTAL != value))
				{
					this._NM_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLG_IMPO", DbType="Char(1)")]
		public System.Nullable<char> FLG_IMPO
		{
			get
			{
				return this._FLG_IMPO;
			}
			set
			{
				if ((this._FLG_IMPO != value))
				{
					this._FLG_IMPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PART_PRFM", DbType="Int")]
		public System.Nullable<int> ID_PART_PRFM
		{
			get
			{
				return this._ID_PART_PRFM;
			}
			set
			{
				if ((this._ID_PART_PRFM != value))
				{
					this._ID_PART_PRFM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_ESTA_CONTA", DbType="Char(1)")]
		public System.Nullable<char> CD_ESTA_CONTA
		{
			get
			{
				return this._CD_ESTA_CONTA;
			}
			set
			{
				if ((this._CD_ESTA_CONTA != value))
				{
					this._CD_ESTA_CONTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_INGRESO", DbType="Int")]
		public System.Nullable<int> ID_INGRESO
		{
			get
			{
				return this._ID_INGRESO;
			}
			set
			{
				if ((this._ID_INGRESO != value))
				{
					this._ID_INGRESO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_CONDICION", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string DS_CONDICION
		{
			get
			{
				return this._DS_CONDICION;
			}
			set
			{
				if ((this._DS_CONDICION != value))
				{
					this._DS_CONDICION = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_COMP_DETA_QUEDAN")]
	public partial class V_COMP_DETA_QUEDAN
	{
		
		private int _ID;
		
		private System.Nullable<int> _ID_COMPRA;
		
		private System.Nullable<int> _ID_QUEDAN;
		
		private string _CD_SERIE;
		
		private System.Nullable<int> _CD_NUMERO;
		
		private string _DS_DOCUMENTO;
		
		private string _DS_CONDICION;
		
		private char _FLG_CREDITO;
		
		private System.Nullable<System.DateTime> _FE_FECHA;
		
		private System.Nullable<System.DateTime> _FE_VENCIMIENTO;
		
		private string _DS_NOMBRE;
		
		private System.Nullable<decimal> _NM_TOTAL;
		
		private System.Nullable<decimal> _NM_SALDO;
		
		public V_COMP_DETA_QUEDAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_COMPRA", DbType="Int")]
		public System.Nullable<int> ID_COMPRA
		{
			get
			{
				return this._ID_COMPRA;
			}
			set
			{
				if ((this._ID_COMPRA != value))
				{
					this._ID_COMPRA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_QUEDAN", DbType="Int")]
		public System.Nullable<int> ID_QUEDAN
		{
			get
			{
				return this._ID_QUEDAN;
			}
			set
			{
				if ((this._ID_QUEDAN != value))
				{
					this._ID_QUEDAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_SERIE", DbType="VarChar(10)")]
		public string CD_SERIE
		{
			get
			{
				return this._CD_SERIE;
			}
			set
			{
				if ((this._CD_SERIE != value))
				{
					this._CD_SERIE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_NUMERO", DbType="Int")]
		public System.Nullable<int> CD_NUMERO
		{
			get
			{
				return this._CD_NUMERO;
			}
			set
			{
				if ((this._CD_NUMERO != value))
				{
					this._CD_NUMERO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_DOCUMENTO", DbType="VarChar(100)")]
		public string DS_DOCUMENTO
		{
			get
			{
				return this._DS_DOCUMENTO;
			}
			set
			{
				if ((this._DS_DOCUMENTO != value))
				{
					this._DS_DOCUMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_CONDICION", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string DS_CONDICION
		{
			get
			{
				return this._DS_CONDICION;
			}
			set
			{
				if ((this._DS_CONDICION != value))
				{
					this._DS_CONDICION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLG_CREDITO", DbType="Char(1) NOT NULL")]
		public char FLG_CREDITO
		{
			get
			{
				return this._FLG_CREDITO;
			}
			set
			{
				if ((this._FLG_CREDITO != value))
				{
					this._FLG_CREDITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FE_FECHA", DbType="DateTime")]
		public System.Nullable<System.DateTime> FE_FECHA
		{
			get
			{
				return this._FE_FECHA;
			}
			set
			{
				if ((this._FE_FECHA != value))
				{
					this._FE_FECHA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FE_VENCIMIENTO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FE_VENCIMIENTO
		{
			get
			{
				return this._FE_VENCIMIENTO;
			}
			set
			{
				if ((this._FE_VENCIMIENTO != value))
				{
					this._FE_VENCIMIENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DS_NOMBRE", DbType="VarChar(200)")]
		public string DS_NOMBRE
		{
			get
			{
				return this._DS_NOMBRE;
			}
			set
			{
				if ((this._DS_NOMBRE != value))
				{
					this._DS_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_TOTAL", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_TOTAL
		{
			get
			{
				return this._NM_TOTAL;
			}
			set
			{
				if ((this._NM_TOTAL != value))
				{
					this._NM_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_SALDO", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> NM_SALDO
		{
			get
			{
				return this._NM_SALDO;
			}
			set
			{
				if ((this._NM_SALDO != value))
				{
					this._NM_SALDO = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
